/**
 * TypeScriptGenerator
 *
 * Bespoke, convention-aware TypeScript codegen for OCF schemas. Builds on the
 * `SchemaComposer` so that each object's inherited (`allOf`) properties are
 * already flattened, then emits one named TS declaration per schema:
 *
 *   - enums              -> `export type Name = "A" | "B" | ...`
 *   - scalar types       -> `export type Name = string | number | boolean`
 *   - object/type/file   -> `export interface Name { ... }`
 *
 * Property values are mapped structurally, following OCF conventions:
 *
 *   - `$ref`             -> the named type for the referenced schema
 *   - `const`            -> a literal type (`"TX_STOCK_ISSUANCE"`)
 *   - inline `enum`      -> a union of literals
 *   - `oneOf` / `anyOf`  -> a union of the member types
 *   - `type: "array"`    -> `Item[]`
 *   - nested object      -> an inline object type
 *
 * Because every schema becomes a named type and `$ref`s become references to
 * those names, the output mirrors the OCF schema graph rather than inlining
 * everything — far more readable and maintainable than generic JSON-Schema
 * codegen. Output is a single self-contained module (declaration order does
 * not matter for `type`/`interface` declarations).
 *
 * The abstract "primitive" base schemas are omitted by default: they exist
 * only to be inherited via `allOf`, and the composer has already flattened
 * their properties into each concrete type, so nothing references them. Pass
 * `includePrimitives: true` to emit them anyway.
 *
 * Framework-free: plain schema JSON in, a TypeScript source string out.
 */

import {
  buildSchemaRegistry,
  composeAll,
  ComposedSchemaJson,
  isBackwardsCompatibleWrapper,
  RawSchemaJson,
} from "./SchemaComposer.js";

export type GenerateTypeScriptOptions = {
  /** Prefix applied to every generated type name. Defaults to `"OCF"`, which
   *  keeps names collision-free against TS/DOM globals like `Object`, `Date`,
   *  and `File` (all of which exist as OCF schema names). */
  typePrefix?: string;
  /** Emit JSDoc comments from schema/property `description`s. Default `true`. */
  includeDescriptions?: boolean;
  /** Banner comment placed at the top of the file. A sensible default is used
   *  when omitted; pass `""` to suppress. */
  banner?: string;
  /** Behavior when a `$ref` can't be resolved: `"unknown"` (default) emits
   *  the `unknown` type and records a warning; `"throw"` fails. */
  onMissingRef?: "unknown" | "throw";
  /** Emit the abstract "primitive" base schemas (the `allOf` inheritance bases
   *  under `/schema/primitives`). Default `false`: their properties are
   *  flattened into every concrete type via composition, so nothing references
   *  them — emitting them only adds orphaned, easily-misused base shapes. */
  includePrimitives?: boolean;
};

const DEFAULT_PREFIX = "OCF";

const DEFAULT_BANNER = `/**
 * Open Cap Format (OCF) — TypeScript types.
 *
 * AUTO-GENERATED by \`npm run schema:gen-types\`. Do not edit by hand;
 * regenerate from the JSON Schemas under /schema after any change.
 */
/* eslint-disable */`;

/** Short notice placed under the banner so consumers of the generated module
 *  understand the primitives policy — why there are no abstract base types
 *  (or, conversely, why they are present) and how to flip it. */
function primitivesNotice(includePrimitives: boolean): string {
  return includePrimitives
    ? `/* NOTE: the abstract "primitive" base schemas (under /schema/primitives)
 * are INCLUDED below (generated with --include-primitives). They are
 * inheritance-only bases; a bare base type is never itself a valid OCF value. */`
    : `/* NOTE: the abstract "primitive" base schemas (the \`allOf\` inheritance
 * bases under /schema/primitives) are intentionally omitted. Their properties
 * are flattened into each concrete type, so nothing references them and a bare
 * base type is never itself a valid OCF value. Regenerate with
 * \`--include-primitives\` if you need the base shapes. */`;
}

/** The five top-level partitions of /schema, used to group output. */
const CATEGORY_ORDER = [
  "enums",
  "types",
  "primitives",
  "objects",
  "files",
] as const;
type Category = typeof CATEGORY_ORDER[number] | "other";

const CATEGORY_HEADINGS: { [k in Category]: string } = {
  enums: "Enums",
  types: "Types",
  primitives: "Primitives (abstract base shapes)",
  objects: "Objects",
  files: "File wrappers",
  other: "Other",
};

// ---------------------------------------------------------------------------
// Naming
// ---------------------------------------------------------------------------

function basenameFromId(id: string): string {
  const last = id.split("/").pop() ?? id;
  return last.replace(/\.schema\.json$/, "");
}

/** The `$id` path segment that places a schema in a /schema partition. */
function categoryFromId(id: string): Category {
  const marker = "/schema/";
  const idx = id.indexOf(marker);
  const tail = idx >= 0 ? id.slice(idx + marker.length) : id;
  const segment = tail.split("/")[0];
  return (CATEGORY_ORDER as readonly string[]).includes(segment)
    ? (segment as Category)
    : "other";
}

/** A schema's partition rank in `CATEGORY_ORDER`; `"other"` sorts last. Used
 *  to decide, on a base-name collision, which schema keeps the clean name. */
function categoryPriority(id: string): number {
  const idx = (CATEGORY_ORDER as readonly string[]).indexOf(categoryFromId(id));
  return idx === -1 ? CATEGORY_ORDER.length : idx;
}

function toPascalCase(value: string): string {
  const cleaned = value
    .replace(/[^A-Za-z0-9]+(.)?/g, (_m, c) => (c ? c.toUpperCase() : ""))
    .replace(/[^A-Za-z0-9]/g, "");
  return cleaned ? cleaned.charAt(0).toUpperCase() + cleaned.slice(1) : cleaned;
}

/**
 * Assign a unique TypeScript type name to every schema `$id`. Names are
 * `<prefix><PascalCaseBasename>`. On the rare base-name collision (two schemas
 * with the same basename in different partitions, e.g. `types/File` and
 * `primitives/files/File`), the schema in the earliest partition
 * (`CATEGORY_ORDER`: enums < types < primitives < objects < files) keeps the
 * clean name and the others fold in their parent directory segment to
 * disambiguate (`OCFFile` and `OCFFilesFile`). A schema whose name already
 * begins with the prefix is not double-prefixed (e.g. `OCFManifestFile` ->
 * `OCFManifestFile`, not `OCFOCFManifestFile`).
 */
function assignTypeNames(
  schemas: RawSchemaJson[],
  prefix: string
): Map<string, string> {
  const prefixed = (name: string) =>
    prefix && name.startsWith(prefix) ? name : prefix + name;
  const baseName = (id: string) => prefixed(toPascalCase(basenameFromId(id)));
  const foldedName = (id: string) => {
    const parts = id.split("/");
    const parent = parts[parts.length - 2] ?? "";
    return prefixed(toPascalCase(parent) + toPascalCase(basenameFromId(id)));
  };

  // Assign in partition-priority order so the earliest-partition schema claims
  // the clean base name and any later collider falls back to its folded name.
  // `$id` breaks ties for determinism, independent of input order.
  const ordered = [...schemas].sort((a, b) => {
    const pa = categoryPriority(a.$id);
    const pb = categoryPriority(b.$id);
    return pa !== pb ? pa - pb : a.$id.localeCompare(b.$id);
  });

  const idToName = new Map<string, string>();
  const assigned = new Set<string>();
  for (const schema of ordered) {
    let name = assigned.has(baseName(schema.$id))
      ? foldedName(schema.$id)
      : baseName(schema.$id);
    // Final safety net against any residual duplication.
    let unique = name;
    let n = 2;
    while (assigned.has(unique)) unique = `${name}${n++}`;
    assigned.add(unique);
    idToName.set(schema.$id, unique);
  }
  return idToName;
}

// ---------------------------------------------------------------------------
// Value -> TypeScript type expression
// ---------------------------------------------------------------------------

const IDENTIFIER_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function propertyKey(key: string): string {
  return IDENTIFIER_RE.test(key) ? key : JSON.stringify(key);
}

function scalarType(jsonType: string): string {
  switch (jsonType) {
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    case "string":
    default:
      return "string";
  }
}

/** A type expression that must be parenthesized before appending `[]`. */
function needsParens(expr: string): boolean {
  return expr.includes("|") || expr.includes("&") || expr.includes(" ");
}

function uniqueUnion(members: string[]): string {
  const seen = new Set<string>();
  const ordered: string[] = [];
  for (const member of members) {
    if (!seen.has(member)) {
      seen.add(member);
      ordered.push(member);
    }
  }
  return ordered.length ? ordered.join(" | ") : "never";
}

type Context = {
  idToName: Map<string, string>;
  /** Schema `$id`s intentionally not emitted (e.g. omitted primitives). A
   *  direct `$ref` to one of these resolves to `unknown` with a warning,
   *  rather than a dangling reference to an undeclared type. */
  omittedIds: Set<string>;
  onMissingRef: "unknown" | "throw";
  warnings: string[];
};

/** Map a single JSON-Schema property value to a TypeScript type expression. */
function tsTypeForValue(value: any, ctx: Context): string {
  if (value === null || typeof value !== "object") return "unknown";

  if (typeof value.$ref === "string") {
    const name = ctx.idToName.get(value.$ref);
    if (name) return name;
    // A direct $ref to a schema we intentionally omitted (e.g. a primitive
    // base referenced outside of an allOf). Surface it rather than dangle.
    if (ctx.omittedIds.has(value.$ref)) {
      if (ctx.onMissingRef === "throw") {
        throw new Error(`$ref to omitted primitive base: ${value.$ref}`);
      }
      ctx.warnings.push(
        `$ref to omitted primitive base -> unknown: ${value.$ref}`
      );
      return "unknown";
    }
    if (ctx.onMissingRef === "throw") {
      throw new Error(`Unresolved $ref in codegen: ${value.$ref}`);
    }
    ctx.warnings.push(`Unresolved $ref -> unknown: ${value.$ref}`);
    return "unknown";
  }

  if ("const" in value) return JSON.stringify(value.const);

  if (Array.isArray(value.enum)) {
    return uniqueUnion(value.enum.map((member: any) => JSON.stringify(member)));
  }

  if (Array.isArray(value.oneOf)) {
    return uniqueUnion(
      value.oneOf.map((member: any) => tsTypeForValue(member, ctx))
    );
  }
  if (Array.isArray(value.anyOf)) {
    return uniqueUnion(
      value.anyOf.map((member: any) => tsTypeForValue(member, ctx))
    );
  }
  if (Array.isArray(value.allOf)) {
    const parts = value.allOf.map((member: any) => tsTypeForValue(member, ctx));
    return parts.length ? parts.join(" & ") : "unknown";
  }

  const jsonType = value.type;

  if (Array.isArray(jsonType)) {
    return uniqueUnion(jsonType.map((t: string) => scalarType(t)));
  }

  if (jsonType === "array") {
    const item = value.items ? tsTypeForValue(value.items, ctx) : "unknown";
    return needsParens(item) ? `(${item})[]` : `${item}[]`;
  }

  if (jsonType === "object" || value.properties) {
    return inlineObjectType(value, ctx);
  }

  if (typeof jsonType === "string") return scalarType(jsonType);

  return "unknown";
}

/** Render an anonymous nested object schema as an inline TS object type. */
function inlineObjectType(value: any, ctx: Context): string {
  const properties = value.properties ?? {};
  const required = new Set<string>(value.required ?? []);
  const members = Object.entries(properties).map(([key, propValue]) => {
    const optional = required.has(key) ? "" : "?";
    return `${propertyKey(key)}${optional}: ${tsTypeForValue(propValue, ctx)};`;
  });
  if (value.additionalProperties && value.additionalProperties !== true) {
    members.push(
      `[key: string]: ${tsTypeForValue(value.additionalProperties, ctx)};`
    );
  } else if (value.additionalProperties === true) {
    members.push(`[key: string]: unknown;`);
  }
  return members.length ? `{ ${members.join(" ")} }` : "Record<string, never>";
}

// ---------------------------------------------------------------------------
// JSDoc
// ---------------------------------------------------------------------------

function jsdoc(
  lines: Array<string | undefined | null | false>,
  indent: string
): string {
  const content = lines.filter(Boolean) as string[];
  if (!content.length) return "";
  // Split any embedded newlines so each becomes its own ` * ` line.
  const flattened = content.flatMap((line) => line.split("\n"));
  const body = flattened.map((line) => `${indent} * ${line}`).join("\n");
  return `${indent}/**\n${body}\n${indent} */\n`;
}

/** Annotation tags (format/pattern/min*) worth surfacing in a type's JSDoc. */
function annotationTags(value: any): string[] {
  const tags: string[] = [];
  if (typeof value.format === "string") tags.push(`@format ${value.format}`);
  if (typeof value.pattern === "string") tags.push(`@pattern ${value.pattern}`);
  if (value.minimum !== undefined) tags.push(`@minimum ${value.minimum}`);
  if (value.maximum !== undefined) tags.push(`@maximum ${value.maximum}`);
  if (value.minItems !== undefined) tags.push(`@minItems ${value.minItems}`);
  if (value.maxItems !== undefined) tags.push(`@maxItems ${value.maxItems}`);
  if (value.minLength !== undefined) tags.push(`@minLength ${value.minLength}`);
  if (value.maxLength !== undefined) tags.push(`@maxLength ${value.maxLength}`);
  if (value.uniqueItems) tags.push(`@uniqueItems`);
  if (value.deprecated) tags.push(`@deprecated`);
  return tags;
}

// ---------------------------------------------------------------------------
// Declarations
// ---------------------------------------------------------------------------

function declareEnum(name: string, schema: ComposedSchemaJson): string {
  const members = (schema.enum as any[]).map((member) =>
    JSON.stringify(member)
  );
  const union = members.length
    ? members.map((m) => `  | ${m}`).join("\n")
    : "  never";
  return `export type ${name} =\n${union};`;
}

function declareInterface(
  name: string,
  schema: ComposedSchemaJson,
  ctx: Context,
  includeDescriptions: boolean
): string {
  const required = new Set<string>(schema.required ?? []);
  const entries = Object.entries(schema.properties ?? {});
  const lines = entries.map(([key, value]: [string, any]) => {
    const doc = includeDescriptions
      ? jsdoc([value?.description, ...annotationTags(value ?? {})], "  ")
      : "";
    const optional = required.has(key) ? "" : "?";
    return `${doc}  ${propertyKey(key)}${optional}: ${tsTypeForValue(
      value,
      ctx
    )};`;
  });

  if (schema.additionalProperties && schema.additionalProperties !== true) {
    lines.push(
      `  [key: string]: ${tsTypeForValue(schema.additionalProperties, ctx)};`
    );
  } else if (schema.additionalProperties === true) {
    lines.push(`  [key: string]: unknown;`);
  }

  const body = lines.length ? `\n${lines.join("\n")}\n` : "\n";
  return `export interface ${name} {${body}}`;
}

/**
 * Render a backwards-compatibility wrapper as an alias to the schema it wraps,
 * with the `object_type` discriminant pinned to the wrapper's literal. Using an
 * intersection (`Parent & { object_type: "..." }`) keeps every inherited
 * property and narrows the parent's discriminant union down to the single
 * legacy value, which is exactly what the `allOf` + `const` override means.
 */
function declareWrapperAlias(
  name: string,
  schema: ComposedSchemaJson,
  ctx: Context,
  includeDescriptions: boolean
): string {
  const parentRef = (schema.allOf?.[0] as { $ref?: string } | undefined)?.$ref;
  const parentName = parentRef ? ctx.idToName.get(parentRef) : undefined;
  const objectType = (schema.properties as any)?.object_type ?? {};
  const literal = tsTypeForValue(objectType, ctx);
  const memberDoc = includeDescriptions
    ? jsdoc([objectType.description], "  ")
    : "";
  const member = `${memberDoc}  object_type: ${literal};`;

  if (!parentName) {
    if (ctx.onMissingRef === "throw") {
      throw new Error(
        `Unresolved wrapper parent in codegen: ${parentRef ?? "(none)"}`
      );
    }
    ctx.warnings.push(
      `Unresolved wrapper parent -> object_type only: ${schema.$id}`
    );
    return `export type ${name} = {\n${member}\n};`;
  }

  return `export type ${name} = ${parentName} & {\n${member}\n};`;
}

function declareSchema(
  schema: ComposedSchemaJson,
  ctx: Context,
  includeDescriptions: boolean
): string {
  const name = ctx.idToName.get(schema.$id)!;
  const doc = includeDescriptions
    ? jsdoc([schema.title, schema.description], "")
    : "";

  // Backwards-compat wrapper (a single `allOf` parent plus only an
  // `object_type` discriminant): emit an alias to the parent with the
  // discriminant pinned. These schemas are intentionally left un-flattened by
  // the composer, so treating them as a normal interface here would drop every
  // inherited property and produce a near-empty, useless type.
  if (isBackwardsCompatibleWrapper(schema)) {
    return doc + declareWrapperAlias(name, schema, ctx, includeDescriptions);
  }

  // Enum
  if (Array.isArray(schema.enum)) {
    return doc + declareEnum(name, schema);
  }

  // Object / interface (objects, files, object-shaped types — anything with
  // its own properties after composition)
  const hasProperties =
    schema.properties && Object.keys(schema.properties).length > 0;
  if (schema.type === "object" || hasProperties) {
    return doc + declareInterface(name, schema, ctx, includeDescriptions);
  }

  // Root-level union (not used by OCF roots today, but handle it)
  if (Array.isArray(schema.oneOf) || Array.isArray((schema as any).anyOf)) {
    const expr = tsTypeForValue(
      { oneOf: schema.oneOf ?? (schema as any).anyOf },
      ctx
    );
    return `${doc}export type ${name} = ${expr};`;
  }

  // Scalar type alias (Date, Numeric, CountryCode, ...)
  if (typeof schema.type === "string") {
    const docWithTags = includeDescriptions
      ? jsdoc([schema.title, schema.description, ...annotationTags(schema)], "")
      : "";
    return `${docWithTags}export type ${name} = ${scalarType(schema.type)};`;
  }

  ctx.warnings.push(`Unrecognized schema shape -> unknown: ${schema.$id}`);
  return `${doc}export type ${name} = unknown;`;
}

// ---------------------------------------------------------------------------
// Entry point
// ---------------------------------------------------------------------------

export type GenerateTypeScriptResult = {
  /** The full TypeScript module source. */
  source: string;
  /** `$id` -> generated type name, for callers that want the mapping. */
  typeNames: { [id: string]: string };
  /** Non-fatal issues encountered (e.g. unresolved `$ref`s). */
  warnings: string[];
};

/**
 * Generate a single self-contained TypeScript module declaring a named type
 * for every schema in `rawSchemas`.
 */
export function generateTypeScript(
  rawSchemas: RawSchemaJson[],
  options: GenerateTypeScriptOptions = {}
): GenerateTypeScriptResult {
  const {
    typePrefix = DEFAULT_PREFIX,
    includeDescriptions = true,
    banner,
    onMissingRef = "unknown",
    includePrimitives = false,
  } = options;

  // Compose so each object's inherited properties are flattened in; keep refs
  // (we map them to named types rather than inlining). Missing inheritance refs
  // must fail codegen, otherwise generated types can silently drop base fields.
  buildSchemaRegistry(rawSchemas); // validates: throws on duplicate $id
  const { composed } = composeAll(rawSchemas);

  const idToName = assignTypeNames(rawSchemas, typePrefix);

  // Primitives are inheritance-only bases: the composer has already flattened
  // their properties into every concrete type above, so by default we don't
  // emit them. Drop them from the name map too — that way a stray *direct*
  // `$ref` to a primitive surfaces as a warning instead of a dangling
  // reference. Names are assigned over the full set first, so concrete type
  // names are identical whether or not primitives are emitted.
  const omittedIds = new Set<string>();
  if (!includePrimitives) {
    for (const schema of rawSchemas) {
      if (categoryFromId(schema.$id) === "primitives") {
        omittedIds.add(schema.$id);
        idToName.delete(schema.$id);
      }
    }
  }

  const ctx: Context = { idToName, omittedIds, onMissingRef, warnings: [] };

  // Group declarations by partition, sorted by name within each group, for a
  // stable and readable file.
  const byCategory = new Map<Category, string[]>();
  for (const schema of composed) {
    if (omittedIds.has(schema.$id)) continue;
    const category = categoryFromId(schema.$id);
    const declaration = declareSchema(schema, ctx, includeDescriptions);
    if (!byCategory.has(category)) byCategory.set(category, []);
    byCategory.get(category)!.push(declaration);
  }

  const sections: string[] = [];
  const categories: Category[] = [...CATEGORY_ORDER, "other"];
  for (const category of categories) {
    const declarations = byCategory.get(category);
    if (!declarations || !declarations.length) continue;
    declarations.sort((a, b) => declaredName(a).localeCompare(declaredName(b)));
    const heading = `// ${"=".repeat(73)}\n// ${
      CATEGORY_HEADINGS[category]
    }\n// ${"=".repeat(73)}`;
    sections.push(`${heading}\n\n${declarations.join("\n\n")}`);
  }

  // A caller-supplied banner is used verbatim (pass "" to suppress); otherwise
  // the default banner gets the primitives-policy notice appended.
  const effectiveBanner =
    banner !== undefined
      ? banner
      : `${DEFAULT_BANNER}\n\n${primitivesNotice(includePrimitives)}`;
  const parts = [effectiveBanner, sections.join("\n\n")].filter(Boolean);
  const source = parts.join("\n\n") + "\n";

  const typeNames: { [id: string]: string } = {};
  for (const [id, name] of idToName) typeNames[id] = name;

  return { source, typeNames, warnings: ctx.warnings };
}

/** Pull the declared type name out of a declaration string, for sorting. */
function declaredName(declaration: string): string {
  const match = declaration.match(/export (?:interface|type) (\w+)/);
  return match ? match[1] : declaration;
}
