name: Write OCF Schema File Copyright Notices

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  enforce-ocf-schema-file-copyright-notices:
    name: Write OCF Schema File Copyright Notices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install Dependencies
        run: npm install

      - name: Check for coypright notices
        run: npm run enforce-copyright-notices

      - name: Prettier Fix Formatting
        run: npm run fix
